version: 1.3.0.{build}-{branch}

# Environment setup
image: Visual Studio 2017
clone_folder: c:\projects\powerping

# Update assembly info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.3.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

# Build config
configuration: Release
platform:
  - x86
  - x64
build:
   project: PowerPing.sln
   verbosity: minimal

#Artifact/Publishing 
artifacts:
  - path: \build\x86\PowerPing.exe
    name: PowerPing(x86)
  - path: \build\x64\PowerPing.exe
    name: PowerPing(x64)
    

deploy:
  - provider: GitHub
    tag: v$(appveyor_build_version)
    release: Nightly build
    description: Most recent build of master branch, may contain bugs (geolocation might not work)
    auth_token:
        secure: wjZlrP/YZtBhNOjhhCNdr83E7CkgdjTwg0GVq1sOJDaLQVlJ0XKJNTSkawTCigA/
    repository: Killeroo/PowerPing
    artifact: PowerPing(x64)
    prerelease: true
