version: 1.2.1.{build}-{branch}

# Environment setup
image: Visual Studio 2015
clone_folder: c:\projects\powerping

# Update assembly info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.2.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# Build config
configuration: Release
platform:
  - x86
  - x64
build:
   project: PowerPing.sln
   verbosity: minimal

#Artifact/Publishing 
artifacts:
  - path: \build\x86\PowerPing.exe
    name: PowerPing(x86)
  - path: \build\x64\PowerPing.exe
    name: PowerPing(x64)
